# 博客标题
title: MUYI
# 博客描述
description: 这里是MUYI的技术博客，分享编程经验、代码技巧、软件项目开发历程和技术学习心得。
# 你的GitHub用户名
github_username: Mein-Augenstern

# 以下是可选配置部分

# 网站URL（如果有自定义域名），如果没有可以不填
url: [你的博客网址，如果使用默认的 GitHub Pages 格式则可省略]
# 关于作者的详细介绍，可以使用多行文本
author:
  name: guoyangyang
  bio: |
    我是一名热爱编程的软件工程师，热衷于探索新技术，擅长Java开发。在这个博客中，我将分享自己在编程旅程中的点点滴滴，希望能和大家一起进步。
# 社交账号链接（可选，如果有相关社交账号）
social:
  twitter: [你的推特账号，如果有]
  linkedin: [你的领英账号，如果有]
  facebook: [你的脸书账号，如果有]
# 主题相关配置（可根据实际使用的主题调整）
theme_config:
  # 导航栏菜单项，可以添加更多链接，比如项目展示、技术分类等
  nav:
    - text: "首页"
      link: "/"
    - text: "关于我"
      link: "/about"
    - text: "文章分类"
      link: "/categories"
    - text: "联系我"
      link: "/contact"
